package com.finguard.core.common.exception;

public enum ErrorCode {
    VALIDATION_FAILED,
    INVALID_REQUEST,
    INVALID_CREDENTIALS,
    AUTHENTICATION_REQUIRED,
    INVALID_TOKEN,
    ACCESS_DENIED,
    ACCOUNT_NOT_FOUND,
    TRANSACTION_NOT_FOUND,
    DUPLICATE_ACCOUNT_NO,
    DUPLICATE_TRANSACTION,
    INVALID_ACCOUNT_INPUT,
    INVALID_TRANSACTION_INPUT,
    INVALID_ACCOUNT_OPERATION,
    INVALID_TRANSACTION_OPERATION,
    INVALID_IMPORT_FILE,
    IMPORT_JOB_NOT_FOUND,
    RECONCILIATION_JOB_NOT_FOUND,
    INVALID_RECONCILIATION_OPERATION,
    REVIEW_TASK_NOT_FOUND,
    INVALID_REVIEW_OPERATION,
    REVIEW_VERSION_CONFLICT,
    DATA_INTEGRITY_CONFLICT,
    RESOURCE_NOT_FOUND,
    INTERNAL_SERVER_ERROR
}
