package com.finguard.core.common.exception;

public enum ErrorCode {
    VALIDATION_FAILED,
    INVALID_REQUEST,
    INVALID_CREDENTIALS,
    AUTHENTICATION_REQUIRED,
    INVALID_TOKEN,
    ACCESS_DENIED,
    ACCOUNT_NOT_FOUND,
    TRANSACTION_NOT_FOUND,
    DUPLICATE_ACCOUNT_NO,
    DUPLICATE_TRANSACTION,
    INVALID_ACCOUNT_INPUT,
    INVALID_TRANSACTION_INPUT,
    INVALID_ACCOUNT_OPERATION,
    INVALID_TRANSACTION_OPERATION,
    DATA_INTEGRITY_CONFLICT,
    RESOURCE_NOT_FOUND,
    INTERNAL_SERVER_ERROR
}
