package com.finguard.core.importjob.model;

public enum ImportRowErrorCode {
    COLUMN_COUNT_MISMATCH,
    INVALID_ACCOUNT_NO,
    ACCOUNT_NOT_FOUND,
    ACCOUNT_NOT_ACTIVE,
    INVALID_EXTERNAL_TRANSACTION_NO,
    INVALID_DIRECTION,
    INVALID_AMOUNT,
    INVALID_TRANSACTION_TIME,
    DESCRIPTION_TOO_LONG,
    DUPLICATE_TRANSACTION_IN_FILE,
    DUPLICATE_TRANSACTION
}
